### ISSUE TITLE
Couldn't able to create account via API

### ISSUE THREAD

**Issue by nithya-cc** [polonel/trudesk#131]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:
  I couldn't able to create account via API. received response like below
 `{"success":false,"error":"Invalid Group Array"}`

**What did you expect to happen**:
   I want to create the account by using API

**How to reproduce it (as minimally and precisely as possible)**:
   I have called  create account API call by using 

> request method in Node JS

. But received response like 
   below
  `{"success":false,"error":"Invalid Group Array"}`

   I have given the correct group id as the create API call param like   
    `aGrps :["5c46e6c4601d4c00253dd7bb"]`

**Anything else we need to know?**:
   This is my code. You can check & let me know Which part is wrong.
```
var options = { method: 'POST',
url: 'https://{{MY_URI}}/api/v1/users/create',
headers:
{
accesstoken: 'MY_ACCESS_TOKEN',
'content-type': 'application/x-www-form-urlencoded' },
form:
{ aUsername: 'nithya',
aPass: 'nithya@123',
aPassConfirm: 'nithya@123',
aFullname: 'NithyaS',
aEmail: 'nithya@gmail.com',
aRole: 'support',
aTitle: 'creation',
aGrps :["5c46e6c4601d4c00253dd7bb"]
} };

request(options, function (error, response, body) {
if (error) throw new Error(error);
console.log(response);
console.log(body);
});
```
**Environment**:
- Trudesk Version: v1.0.5 (your master branch code)
- OS (e.g. from /etc/os-release):
- Node.JS Version: v8.10.0
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
Can you check https://github.com/polonel/trudesk/issues/120 and see if this is the same issue you are having.

**Comment by nithya-cc** [comment]
Hi @polonel,
Thanks for your reply. I had checked that issue already. That same format I have given for `aGrps`.  BUt still received the response like `{"success":false,"error":"Invalid Group Array"}`. Looks like the problem with the format of group array. Could help me to know the format for that group array. For a Note, I have given correct group ID which is in my environment.

**Comment by nithya-cc** [comment]
Hi,
I have fixed the issue. An issue with that request method.

>  I have used Axios method to call the API instead of request in React JS

Now I can create the account by using API.
Thanks.

**Comment by polonel** [comment]
Glad to hear it. Let me know if you have any further issues.

**Comment by the-jojo-jj** [comment]
so ,how to fix it?
using docker for newest version dosn't fix.

thanks.

**Comment by BronacusAmmon** [comment]
Seconding jojo's question, have the aGrps formatting as the following ["5f6cb84824207800231wrt83"] but still getting invalid group array, running the docker install as well.  Using Postman to test but I tried a quick node script using axios to no success.

**Comment by the-jojo-jj** [comment]
@BronacusAmmon did you find the way?

**Comment by BronacusAmmon** [comment]
I managed to get a success returned but it breaks the entire install and had to be reverted

**Comment by polonel** [comment]
What version of the API are you trying to use? This issue was regarding API v1. V2 had not been released when this issue was created. Please fine v2 https://github.com/polonel/trudesk/blob/master/src/controllers/api/v2/accounts.js

**Comment by the-jojo-jj** [comment]
somebody show me  document for create user in v2, please?

**Comment by latham7** [comment]
Easiest way to use v2 API is to open developer tools in Chrome/edge and capture the GET's and POSTS it creates when you do it thru the GUI. Hope this helps, I know this is an old thread!

**Comment by postaenzo** [comment]
hi, I just installed and run the trudesk stable version. But seems that is still some issue using the v1 API and still cannot find any documentation for the v2. I'm testing the API using postman but I'm not able to create a new user ( login and get existing users ok ). If the v1 is working fine, maybe my request is not valid. I tried in many times and the error that I'm getting is always "Invalid Post Data" from this code section in users.js 
 if (
    !_.every(propCheck, function (x) {
      return x in postData
    })
  ) {
    return res.status(400).json({ success: false, error: 'Invalid Post Data' , postdata: postData})
  }
  One of my test request is below: 
{
     "aUsername":    "user.name1",
     "aPass":        "Passworduser1",
     "aPassConfirm": "Passworduser3",
     "aFullname":    "UserFullName",
     "aEmail":       "user1@yopmail.com",
     "aRole":        "{User}",
     "aTitle":       "Mr",
     "aGrps":        "[{'634e70e4bd99b799cea2e78b'}]"
}

but seems that the method is not receiving it ( req.body seems empty. ) 
I hope I'm wrong, and will be appreciate if you can help me to call correctly that api. 
Will be really appreciate if you can tell me if the stable version is working perfectly fine ( api included ) or not. Because I need to integrate few basic apis functionalities like user creation and tickets management. 

thank you for your support.
