### ISSUE TITLE
An Admin user can't view tickets from other users if not in the same group

### ISSUE THREAD

**Issue by LuigiElleBalotta** [polonel/trudesk#182]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:
The situation:
user named "Administrator" inside the group "A", "B", "C".
user named "John" inside the group "B"
user named "Mario" inside the group "D"

I'm logged as "Administrator"
If john creates a ticket i can see his ticket because we are in group "B".
If Mario creates a ticket I can't see anything because I'm not in group "D".

Why? 

**What did you expect to happen**:
If logged user is an admin, i expect to see everything

**How to reproduce it (as minimally and precisely as possible)**:
Explained in the situation part.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.6 
- OS (e.g. from /etc/os-release): Windows server 2008 r2
- Node.JS Version: latest
- MongoDB Version: latest 
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Yes, this is a known issue.
Please see: https://forum.trudesk.io/t/agent-system-redesign/34

**Comment by LuigiElleBalotta** [comment]
It was fixed with newer version than 1.0.6?

**Comment by polonel** [comment]
I also want to add that v1.0.7 added the permission settings as phase 1 of the reference redesign. Although this does not address your current issue, it does, however, add more flexibility of custom roles and what each role can do. 

The requirement of the groups is still present in the latest release (v1.0.10) but its step one in the resolution. Upcoming are `departments` which allow further customization between what agents have access to. In your case, you can add a global department for Admins that have access to all teams and all groups to always see everything but allowing users that want different admin roles to have access to different resources the option.

![image](https://user-images.githubusercontent.com/626303/55705536-ffa8a480-59ac-11e9-9d34-c35e17b871f3.png)

**Here is the reference post about v1.0.7+ PLEASE READ BEFORE UPGRADING**
https://forum.trudesk.io/t/announcement-trudesk-v1-0-7-release/128

**Comment by LuigiElleBalotta** [comment]
I'm updating, i'll let you know, thanks for the moment @polonel

**Comment by LuigiElleBalotta** [comment]
Update to 1.0.7 successfully done! Is there a way to update to 1.0.10?

**Comment by polonel** [comment]
Yes once you update to 1.0.7 you can easily update to 1.0.10. Each release has its own tag.

```
git pull
git checkout:v1.0.10
yarn install
```
Then restart the trudesk server.

**Comment by LuigiElleBalotta** [comment]
So i can do directly 1.0.7 to 1.0.10 without 8 and 9?

**Comment by LuigiElleBalotta** [comment]
I have updated to 1.0.10 but i can't see the icon of Departments

**Comment by akhlaaqbadulla** [comment]
I just updated as well cannot see the department icon!!

**Comment by polonel** [comment]
It’s not released yet. It’s still under active development. I was simply showing what’s *UPCOMING* and how the issue is getting resolved.

**Comment by LuigiElleBalotta** [comment]
Ok, do you have any clue on the release date? ❤️

**Comment by polonel** [comment]
Within the next week. It's a huge overhaul. Just keep an eye on the forums.
